app:
  cors: false
  security:
    token:
      key: KwHJvRXKdIw4B878mycx/U9Yx+otdmluBnGJbJ5wxrZDFeZxZrrUZeFtbjXMlxnL+G7L8PAOxGHbe6tUqlDjjw==

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
