spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/patents;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  main:
    banner-mode: off

server:
  compression:
    enabled: true
  http2:
    enabled: true

app:
  cors: false
  security:
    token:
      gen-on-start: false
      ttl: 604800000
  service:
    cache:
      path: ${java.io.tmpdir}/cache/p3
      time: 86400000
    legacy:
      url: "http://54.75.255.59/payment_check"
    proxy:
      lock-sec: 120
      wait-sec: 7
      daily-request-limit: 950
      zone: "Europe/Moscow"
